name: distribuidora
#configurar um restart always
services:
  postgres:
    image: postgres:16
    container_name: distribuidora_db
    environment:
      - POSTGRES_USER=u_postgresql_distribuidora
      - POSTGRES_PASSWORD=99546350julio
      - POSTGRES_DB=db_distribuidora
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: distribuidora_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://u_postgresql_distribuidora:99546350julio@postgres:5432/db_distribuidora?schema=public
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: distribuidora_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
